### ISSUE TITLE
Requisitos - Completitud

### ISSUE THREAD

**Issue by LauraDelues** [LauraDelues/notas-vv#4]
El usuario puede cancelar la creación, modificación o eliminación de una categoría o de una nota.
@fiusa8

**Comment by LauraDelues** [comment]
Corregido.

**Comment by LauraDelues** [comment]
La eliminación de una categoría o una nota no esta permitida.

**Comment by miguel-latre** [comment]
¿Seguro que se puede cancelar la creación o modificación de notas y categorías? Podéis ponerlo entre los requisitos (de hecho, en una clase de problamas de IS se planteó así), aunque no es el comportamiento por defecto de las aplicaciones Android y no es como está implementado en el código de partida de la aplicación Notas. De todas formas, sí que es cierto que si permitís que se cancele la creación o modificación de notas, deberíais permitir que también se cancelen las de categorías.
