### ISSUE TITLE
Requisitos - Verificabilidad

### ISSUE THREAD

**Issue by LauraDelues** [LauraDelues/notas-vv#5]
El usuario no puede comprobar si se ha enviado la nota.
@alvaro06

**Comment by LauraDelues** [comment]
Corregido.

**Comment by miguel-latre** [comment]
Se trata de una buena mejora en cuanto a requisitos, pero el punto de la lista de comprobación hace referencia a la _verificabilidad_ no exclusivamente por parte del usuario, sino desde el punto de vista del sistema y de su desarrollo ("debe ser posible comprobar que el requisito se ha satisfecho" = "debe ser posible comprobar que el requisito se ha implementado y funciona correctamente").
